# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10

  - name: Projects
    url: /projects
    weight: 20

  - name: Blogs
    url: /blogs
    weight: 30

  - name: Ask Me Anything
    url: /ama
    weight: 40

