# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blogs
    url: /blog
  - name: Ask me Anything
    url: /ama
    weight: 20
  - name: Projects
    url: /projects
    weight: 30
